insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/administrasi/changepassword',null,'/Administrasi/Ganti Password',230);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/administrasi/role',null,'/Administrasi/Role',210);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/administrasi/user',null,'/Administrasi/User',220);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/report/lossandprofit',null,'/Back Office/Laporan/Laporan Laba Rugi',535);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/report/saleconstraint',null,'/Back Office/Laporan/Laporan Penjualan Constraint',550);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/report/stock',null,'/Back Office/Laporan/Laporan Stok Barang',520);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/report/stockopname',null,'/Back Office/Laporan/Laporan Stok Opname',530);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/report/transaction',null,'/Back Office/Laporan/Laporan Transaksi',510);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/backoffice/stockopname',null,'/Back Office/Stock Opname',540);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/circle',null,'/Master Data/Circle',350);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/customer',null,'/Master Data/Customer',330);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/discount',null,'/Master Data/Discount',340);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/expense',null,'/Master Data/Expense',360);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/stock',null,'/Master Data/Persediaan Barang',310);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/master/supplier',null,'/Master Data/Supplier',320);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/prepaid/sale',null,'/Prepaid/Penjualan Voucher Spesifik',495);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/servicemonitoring/saleconstraintposting',null,'/Service Monitoring/Posting Penjualan Constraint',590);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/setting/database',null,'/Setting/Database',610);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/setting/dbconsistency',null,'/Setting/Database Consistency',640);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/setting/printer',null,'/Setting/Printer',620);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/setting/problemreport',null,'/Setting/Problem Report',630);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/setting/receiptprinterstatus',null,'/Setting/Receipt Printer Status',650);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/constraint/sale',null,'/Transaksi/Constraint/Transaksi Penjualan Constraint',490);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/expense',null,'/Transaksi/Pembayaran Beban Lain-Lain',470);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/payable',null,'/Transaksi/Hutang',450);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/purchase',null,'/Transaksi/Pembelian',410);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/purchasereturn',null,'/Transaksi/Retur Pembelian',420);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/receivable',null,'/Transaksi/Piutang',460);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/revenue',null,'/Transaksi/Input Pendapatan Lain-Lain',480);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/sale',null,'/Transaksi/Penjualan',430);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('/transaction/salereturn',null,'/Transaksi/Retur Penjualan',440);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ChangePasswordForm',null,'Change Password Form',231);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('CircleForm',null,'Circle Form',352);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('CircleList',null,'Circle List',351);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('CustomerForm',null,'Customer Form',332);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('CustomerList',null,'Customer List',331);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('DbConsistencyChecker',null,'Database Consistency Checker',641);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('DbSettingForm',null,'Setting Database Form',611);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('DiscountForm',null,'Discount Form',342);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('DiscountList',null,'Discount List',341);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ExpenseForm',null,'Expense Form',362);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ExpenseList',null,'Expense List',361);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ExpenseTransactionForm',null,'Expense Transaction Form',471);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ItemStockReportList',null,'Item Stock Report List',521);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('PayableForm',null,'Payable Form',452);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('PayableList',null,'Payable List',451);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('PembelianForm',null,'Pembelian Form',411);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('PenjualanForm',null,'Penjualan Form',431);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('PrinterSettingForm',null,'Setting Printer Form',621);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ProblemReportSettingForm',null,'Setting Problem Report Form',631);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ProfitAndLossReportList',null,'Profit and Lost Report List',536);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReceiptPrinterStatus',null,'Receipt Printer Status',651);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReceivableForm',null,'Receivable Form',462);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReceivableList',null,'Receivable List',461);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReportViewer',null,'Report Viewer',539);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReturPembelianForm',null,'Retur Pembelian Form',421);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('ReturPenjualanForm',null,'Retur Penjualan Form',441);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('RevenueTransactionForm',null,'Revenue Transaction Form',481);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('RoleForm',null,'Role Form',212);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('RoleList',null,'Role List',211);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SaleConstraintForm',null,'Sale Constraint Form',491);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SaleConstraintPostingMonitoringForm',null,'Sale Constraint Posting Monitoring Form',592);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SaleConstraintPostingMonitoringList',null,'Sale Constraint Posting Monitoring List',591);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SaleConstraintReportList',null,'Sale Constraint Report List',551);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SaleSpecificPrepaidForm',null,'Sale Specific Prepaid Form',496);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('StockForm',null,'Stock Form',312);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('StockList',null,'Stock List',311);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('StockOpnameConfirmation',null,'Stock Opname Confirmation',542);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('StockOpnameList',null,'Stock Opname List',541);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('StockOpnameReportList',null,'Stock Opname Report List',531);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SupplierForm',null,'Supplier Form',322);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('SupplierList',null,'Supplier List',321);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('TransactionReportList',null,'Transaction Report List',511);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('UserForm',null,'User Form',222);
insert into `permissions`(`CODE`,`DESCRIPTION`,`NAME`,`ORDER_NUM`) values ('UserList',null,'User List',221);
