INSERT INTO v400.roles (DELETED, DESCRIPTION, DISABLED, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME)
SELECT DELETED, DESCRIPTION, DISABLED, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME
FROM minimarketkk.roles;