INSERT INTO migration.items (id, BARCODE, CODE, DELETED, DISABLED, HPP, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, MINIMUM_STOCK, NAME, SELL_PRICE, UNIT)
SELECT ii.id, ii.BARCODE, ii.CODE, ii.DELETED, ii.DISABLED, ss.HPP, ii.ID, ii.LAST_UPDATED_BY, ii.LAST_UPDATED_TIMESTAMP, ss.MINIMUM_STOCK, ii.NAME, ss.SELL_PRICE, ss.UNIT
FROM minimarketkk.items ii
INNER JOIN minimarketkk.item_stocks ss ON ss.ITEM_ID = ii.ID;

UPDATE migration.items SET code = LPAD(id, 10, '0');