INSERT INTO migration.companies (ADDRESS, DELETED, DISABLED, FAX, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, PHONE_1, PHONE_2)
SELECT ADDRESS, DELETED, DISABLED, FAX, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, PHONE_1, PHONE_2
FROM minimarketkk.companies;