INSERT INTO migration.customers (ADDRESS, CODE, DELETED, DESCRIPTION, DISABLED, EMAIL, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, PHONE)
SELECT ADDRESS, CODE, DELETED, DESCRIPTION, DISABLED, EMAIL, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, PHONE
FROM minimarketkk.customers;