INSERT INTO migration.taxes (CODE, DELETED, DESCRIPTION, DISABLED, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, TAX_PERCENT)
SELECT CODE, DELETED, DESCRIPTION, DISABLED, ID, LAST_UPDATED_BY, LAST_UPDATED_TIMESTAMP, NAME, TAX_PERCENT
FROM minimarketkk.taxes;