INSERT INTO `coa_contributions` (`ID`, `NAME`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (0,'NERACA / RIIL',0,0,0,CURRENT_TIMESTAMP());
INSERT INTO `coa_contributions` (`ID`, `NAME`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (1,'RUGI-LABA / NOMINAL',0,0,0,CURRENT_TIMESTAMP());
