ALTER TABLE `stock_opname_details` DROP COLUMN `LAST_STOCK_AMOUNT` ;
ALTER TABLE `items` DROP COLUMN `HPP` ;

insert into `coa`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`NAME`,`COA_GROUP_ID`) values (549,0,0,0,'2014-01-01 22:08:37','BEBAN PEMBELIAN LAIN-LAIN',4);
