USE mama;

insert into `customers`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`ADDRESS`,`CODE`,`DESCRIPTION`,`EMAIL`,`NAME`,`PHONE`) values (0,0,0,1,'2014-01-18 22:29:05','Umum','CUST-0001','UNTUK SEMUA CUSTOMER YANG TIDAK ADA NAMA','-','UMUM','-');
