USE minimarketkk;

insert into `suppliers`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`ADDRESS_1`,`ADDRESS_2`,`CODE`,`CONTACT_PERSON_1`,`CONTACT_PERSON_1_EMAIL`,`CONTACT_PERSON_1_PHONE`,`CONTACT_PERSON_2`,`CONTACT_PERSON_2_EMAIL`,`CONTACT_PERSON_2_PHONE`,`DESCRIPTION`,`EMAIL_1`,`EMAIL_2`,`NAME`,`PHONE_1`,`PHONE_2`) values (1,0,0,1,'2014-01-26 12:09:57','','','SU-001','','','','','','','BELI SENDIRI TANPA SUPPLIER','','','<TIDAK ADA>','','');
