INSERT INTO `coa_groups` (`ID`, `NAME`, `COA_CONTRIBUTION_ID`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (0,'AKTIVA',0,0,0,0,CURRENT_TIMESTAMP());
INSERT INTO `coa_groups` (`ID`, `NAME`, `COA_CONTRIBUTION_ID`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (1,'HUTANG',0,0,0,0,CURRENT_TIMESTAMP());
INSERT INTO `coa_groups` (`ID`, `NAME`, `COA_CONTRIBUTION_ID`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (2,'MODAL',0,0,0,0,CURRENT_TIMESTAMP());
INSERT INTO `coa_groups` (`ID`, `NAME`, `COA_CONTRIBUTION_ID`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (3,'PENDAPATAN',1,0,0,0,CURRENT_TIMESTAMP());
INSERT INTO `coa_groups` (`ID`, `NAME`, `COA_CONTRIBUTION_ID`, `DELETED`, `DISABLED`, `LAST_UPDATED_BY`, `LAST_UPDATED_TIMESTAMP`) VALUES (4,'BEBAN',1,0,0,0,CURRENT_TIMESTAMP());
