USE minimarketkk;

insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (1,0,0,0,'2014-01-01 22:08:37','-','Role List Dialog','RoleListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (2,0,0,0,'2014-01-01 22:08:37','-','Role Form','RoleForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (3,0,0,0,'2014-01-01 22:08:37','-','Stock List Dialog','StockListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (4,0,0,0,'2014-01-01 22:08:37','-','Stock Form','StockForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (5,0,0,0,'2014-01-01 22:08:37','-','Supplier List Dialog','SupplierListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (6,0,0,0,'2014-01-01 22:08:37','-','Supplier Form','SupplierForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (7,0,0,0,'2014-01-01 22:08:37','-','Customer List Dialog','CustomerListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (8,0,0,0,'2014-01-01 22:08:37','-','Customer Form','CustomerForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (9,0,0,0,'2014-01-01 22:08:37','-','Discount List Dialog','DiscountListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (10,0,0,0,'2014-01-01 22:08:37','-','Discount Form','DiscountForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (11,0,0,0,'2014-01-01 22:08:37','-','User List Dialog','UserListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (12,0,0,0,'2014-01-01 22:08:37','-','User Form','UserForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (13,0,0,0,'2014-01-01 22:08:37','-','Purchase Form','PurchaseForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (14,0,0,0,'2014-01-01 22:08:37','-','Purchase Return Form','PurchaseReturnForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (15,0,0,0,'2014-01-01 22:08:37','-','Sale Form','SaleForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (16,0,0,0,'2014-01-01 22:08:37','-','Sale Return Form','SaleReturnForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (17,0,0,0,'2014-01-01 22:08:37','-','Payable List Dialog','PayableListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (18,0,0,0,'2014-01-01 22:08:37','-','Payable Form','PayableForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (19,0,0,0,'2014-01-01 22:08:37','-','Receivable List Dialog','ReceivableListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (20,0,0,0,'2014-01-01 22:08:37','-','Receivable Form','ReceivableForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (21,0,0,0,'2014-01-01 22:08:37','-','Stock Opname List Dialog','StockOpnameListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (22,0,0,0,'2014-01-01 22:08:37','-','Stock Opname Confirmation Dialog','StockOpnameConfirmationDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (23,0,0,0,'2014-01-01 22:08:37','-','Transaction Report List Dialog','TransactionReportListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (24,0,0,0,'2014-01-01 22:08:37','-','Stock Report List Dialog','StockReportListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (25,0,0,0,'2014-01-01 22:08:37','-','Stock Opname Report List Dialog','StockOpnameReportListDialog');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (26,0,0,0,'2014-01-01 22:08:37','-','System Setting Form','SystemSettingForm');
insert into `permissions`(`ID`,`DELETED`,`DISABLED`,`LAST_UPDATED_BY`,`LAST_UPDATED_TIMESTAMP`,`DESCRIPTION`,`NAME`,`CODE`) values (27,0,0,0,'2014-01-01 22:08:37','-','Receipt Printer Test Dialog','ReceiptPrinterTestDialog');
