package com.ganesha.accounting.constants;

public class CoaCodeConstants {

	public static final int KAS_KECIL = 110;
	public static final int KAS_BESAR = 111;
	public static final int PIUTANG_USAHA = 120;
	public static final int PIUTANG_LANGGANAN = 121;
	public static final int PIUTANG_KARYAWAN = 122;
	public static final int PIUTANG_LAIN_LAIN = 129;
	public static final int PERSEDIAAN_BARANG = 130;
	public static final int PERSEDIAAN_LAIN_LAIN = 139;
	public static final int PERALATAN_TOKO = 140;
	public static final int AKUMULASI_PENYUSUTAN_PERALATAN_TOKO = 141;
	public static final int PERLENGKAPAN_TOKO = 150;
	public static final int AKUMULASI_PENYUSUTAN_PERLENGKAPAN_TOKO = 159;
	public static final int HUTANG_USAHA = 210;
	public static final int HUTANG_GAJI = 211;
	public static final int PAJAK_PENJUALAN = 212;
	public static final int HUTANG_LAIN_LAIN = 219;
	public static final int MODAL = 310;
	public static final int LABA_TAHUN_BERJALAN = 311;
	public static final int IKHTISAR_LABA_RUGI = 312;
	public static final int PENJUALAN = 410;
	public static final int RETUR_PEMBELIAN = 412;
	public static final int DISKON_PEMBELIAN = 413;
	public static final int PENDAPATAN_LAIN_LAIN = 419;
	public static final int BIAYA_TELEPON = 510;
	public static final int BIAYA_LISTRIK = 511;
	public static final int BIAYA_PDAM = 512;
	public static final int BEBAN_OPERASIONAL_LAIN_LAIN = 519;
	public static final int IURAN_WARGA = 521;
	public static final int UANG_KEAMANAN = 522;
	public static final int UANG_KEBERSIHAN = 523;
	public static final int BEBAN_LINGKUNGAN_LAIN_LAIN = 529;
	public static final int GAJI_KARYAWAN = 531;
	public static final int THR_DAN_BONUS_KARYAWAN = 532;
	public static final int KESEHATAN_KARYAWAN = 533;
	public static final int BEBAN_KARYAWAN_LAIN_LAIN = 539;
	public static final int ONGKOS_KIRIM_PEMBELIAN = 541;
	public static final int PAJAK_PEMBELIAN = 542;
	public static final int PEMBELIAN = 543;
	public static final int PENYUSUTAN_PERALATAN_TOKO = 551;
	public static final int PENYUSUTAN_PERLENGKAPAN_TOKO = 552;
	public static final int BEBAN_SEWA = 560;
	public static final int RETUR_PENJUALAN = 571;
	public static final int DISKON_PENJUALAN = 572;
	public static final int BEBAN_PENJUALAN_LAIN_LAIN = 579;
	public static final int BEBAN_LAIN_LAIN = 599;
}
